apiVersion: v1
kind: Service
metadata:
  name: {{ include "call-center.fullname" . }}
  labels:
    {{- include "call-center.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.service.dnsName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "call-center.selectorLabels" . | nindent 4 }}
